[build]
  publish = "."
  command = "echo 'Using root directory'"

[[redirects]]
  from = "/"
  to = "/build/web/index.html"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/build/web/index.html"
  status = 200